version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/data/postgres
    env_file:
      - ./.env
volumes:
  database:
  